### ISSUE TITLE
Congratulations and I went ahead with this project

### ISSUE THREAD

**Issue by MakuSensei** [alinstaller/alinstaller#1]
Congratulations for this project,
I went forward, that a good alternative needs to the RIP AnarchyLinux
Saludos desde Argentina

**Comment by MakuSensei** [comment]
I use gnome, so the default DE is not a problem Note that it was missing gparted, also brings many gnome apps that are unnecessary in the ISO.   It would also be nice to have some easy way to add Spanish in the script to create a custom ISO

**Comment by sfanxiang** [comment]
> I use gnome, so the default DE is not a problem Note that it was missing gparted, also brings many gnome apps that are unnecessary in the ISO.

Done.

> It would also be nice to have some easy way to add Spanish in the script to create a custom ISO

https://github.com/alinstaller/alinstaller#translate explains how to add a new language to the GUI. Unfortunately I don't speak Spanish but I think it's straightforward to add it. Created issue #2.
