### ISSUE TITLE
Accessibility support status query

### ISSUE THREAD

**Issue by pranavlal** [alinstaller/alinstaller#11]
Hi,
Do these offline installers support accessibility? In the regular arch installer, if I hit the down arrow key and hit the enter key, a screen reader starts. Does this happen in the offline installer? 

If not, could you please implement that feature or give an alternative way of starting accessibility features?

Pranav

**Comment by sfanxiang** [comment]
If you hit enter directly, wait until GNOME desktop starts, then press Super+Alt+S, the GNOME screen reader should start. See also: https://help.gnome.org/users/gnome-help/stable/a11y-screen-reader.html.en.

Hope this helps! Feel free to reopen if you have any more questions.

**Comment by pranavlal** [comment]
Hi,

 

This helps after installation, but what about during installation?

 

Thanks for including the accessibility packages.

**Comment by sfanxiang** [comment]
> This helps after installation, but what about during installation?

The installer runs on GNOME too, so you can follow the same steps.
