### ISSUE TITLE
Add More Desktop Environments (GNOME Only Currently)

### ISSUE THREAD

**Issue by cheznewa** [alinstaller/alinstaller#12]
Hello It's Possible To Add More Desktop Environments, Like XFCE Plamsa etc?, One Desktop Environment Each ISO.

**Comment by sfanxiang** [comment]
Thanks for asking -- unfortunately adding a new DE takes a tremendous amount of work & maintenance and will double/triple the CI build time. Given the current resources I don't think it's feasible right now.

However, if you have any suggestions to make it easier to install a different DE **after** installing through alinstaller, please let me know. I'd be happy to look into it!
