### ISSUE TITLE
Checksum for downloaded ISO files

### ISSUE THREAD

**Issue by forkthat** [alinstaller/alinstaller#3]
It so happens that downloading from Github is very slow and I am having doubts that the downloaded ISO arrives in its expected manner.  Can you please include a way for us to check the ISO file?

**Comment by sfanxiang** [comment]
#4 adds checksum to future releases. The latest release has sha256sum
`6906bd4cb4c40f386f2b091469c0e069321a7ff3ab7a3d069c9da0b4dfc5e933 *alinstaller-2020.08.03-v29-x86_64.iso`
