### ISSUE TITLE
Minimalistic Arch Install

### ISSUE THREAD

**Issue by forkthat** [alinstaller/alinstaller#5]
Howdy!

Is there a possibility to include a minimalistic install option (or a stripped down ISO instead) for those who would want a pure Arch experience without the hassle of installing it?  As you can see, the ISO is full of programs which might not be useful to others.  Besides, on the second option, it would make the download faster since the file size is smaller.

Thank you for your hard work!

**Comment by sfanxiang** [comment]
> minimalistic install option

The GNOME desktop (and its dependencies!) probably occupies most of this image. To get a smaller image you might need to switch to another DE, which unfortunately isn't trivial to do.

You can find the list of packages explicitly required by alinstaller in [misc/packages_any](https://github.com/alinstaller/alinstaller/blob/master/misc/packages_any). You can remove `firefox`, `gnome-extra`, `noto-fonts-*` and other things you don't need to save some space, except `python-*` and other system stuff which are needed by the installer. But don't expect this to save too much space.

Let me know if you have more questions.

**Comment by forkthat** [comment]
One thing I noticed when booting up the live installer is that there were so many games included.  Were those also included in the gnome dependencies?

**Comment by sfanxiang** [comment]
Good point. I tried to uninstall the games with
```
sudo pacman -Rsc gnome-chess five-or-more four-in-a-row hitori gnome-klotski gnome-mahjongg gnome-mines quadrapassel iagno gnome-robots gnome-sudoku swell-foop tali gnome-taquin gnome-tetravex
```
and I got
```
Total Removed Size:  41.86 MiB
```

> Were those also included in the gnome dependencies?

The games are from `gnome-extra`, but compared with the rest of `gnome-extra` they aren't really much.
